export const APP_CONFIG = {
  apiUrl: import.meta.env.VITE_API_URL || 'http://localhost:5000/api',
  razorpayKeyId: import.meta.env.VITE_RAZORPAY_KEY_ID,
  company: {
    name: import.meta.env.VITE_COMPANY_NAME || 'USJ Technologies Pvt Ltd',
    tagline: import.meta.env.VITE_COMPANY_TAGLINE || "Building India's Future Through Technology",
    email: import.meta.env.VITE_COMPANY_EMAIL || 'info@usjtechnologies.com',
    phone: import.meta.env.VITE_COMPANY_PHONE || '+91-7500000000',
    address: import.meta.env.VITE_COMPANY_ADDRESS || 'Dehradun, Uttarakhand, India',
    social: {
      linkedin: import.meta.env.VITE_COMPANY_LINKEDIN,
      twitter: import.meta.env.VITE_COMPANY_TWITTER,
      instagram: import.meta.env.VITE_COMPANY_INSTAGRAM,
    },
  },
  stats: {
    projects: import.meta.env.VITE_STAT_PROJECTS || '10+',
    clients: import.meta.env.VITE_STAT_CLIENTS || '20+',
    products: import.meta.env.VITE_STAT_PRODUCTS || '200+',
    states: import.meta.env.VITE_STAT_STATES || '12',
  },
  ventures: [
    {
      id: 'bail-beyond',
      name: 'Bail & Beyond Law Chambers',
      tagline: 'Expert Legal Services in Uttarakhand',
      description:
        'Professional legal services focused on bail, criminal law, and legal advisory. Serving clients across Uttarakhand with experienced legal professionals.',
      websiteUrl: import.meta.env.VITE_VENTURE_BAIL_URL || 'https://bailandbeyond.com',
      category: 'Legal Services',
      status: 'live',
      isRevealed: true,
      icon: 'Scale',
      color: '#1A3A5C',
    },
    {
      id: 'chalo-kumbh',
      name: 'Chalo Kumbh',
      tagline: 'Experience the Sacred Kumbh Mela',
      description:
        'Your complete digital companion for Kumbh Mela — bookings, guides, and a vibrant community for pilgrims from across India and the world.',
      websiteUrl: import.meta.env.VITE_VENTURE_KUMBH_URL || 'https://chalokumbh.com',
      category: 'Pilgrimage & Travel',
      status: 'live',
      isRevealed: true,
      icon: 'Compass',
      color: '#C9A84C',
    },
    {
      id: 'doon-travelers',
      name: 'Doon Travelers',
      tagline: 'Explore Uttarakhand & Beyond',
      description:
        'Curated travel packages from Dehradun to the Himalayas, Char Dham, and beyond. Expert local guides and premium experiences.',
      websiteUrl: null,
      category: 'Tours & Travel',
      status: 'coming_soon',
      isRevealed: false,
      icon: 'Mountain',
      color: '#2D7D46',
    },
  ],
};

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  VENTURES: '/ventures',
  PROJECTS: '/projects',
  CERTIFICATIONS: '/certifications',
  CAREERS: '/careers',
  CONTACT: '/contact',
  SHOP: '/shop',
  PRODUCT_DETAIL: (slug) => `/product/${slug}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  WISHLIST: '/wishlist',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_INQUIRIES: '/admin/inquiries',
  ADMIN_VENTURES: '/admin/ventures',
  ADMIN_CERTIFICATIONS: '/admin/certifications',
  ADMIN_TEAM: '/admin/team',
};
